spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    driverClassName: org.h2.Driver
    password: Sparta@456*
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
